# Thalloo Starter Template
#
# This project uses Jekyll to integrate with GitHub Pages.
# Configure the basic settings below to configure your copy.

# Your site settings
title: Evidence Maps - Oxford Long-Term Ecology Laboratory
description: > # this means to ignore newlines until "baseurl:"
  Evidence-based maps and systematic maps produced by the University of Oxford's Long-Term Ecology Laboratory.
baseurl: "/evidencemaps" # the subpath of your site, e.g. /blog
url: "https://oxlel.github.io" # the base hostname & protocol for your site
ownername: "Oxford Long-Term Ecology Laboratory"
ownerurl: "https://oxlel.zoo.ox.ac.uk"

# Internal configuration
plugins:
  - jekyll-remote-theme
remote_theme: AndrewIOM/thalloo
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"